commands:
  - scale --replicas=1 deployment osg-ui
  - scale --replicas=1 deployment osg-api
  - scale --replicas=1 deployment osg-flaskapi
  - set resources deployment osg-db --limits=cpu=512m,memory=512Mi --requests=cpu=512m,memory=512Mi
  - scale --replicas=0 deployment osg-db
  - scale --replicas=1 deployment osg-db
