source: ibm-cp-applications-le-bundle/case/ibm-cp-applications-le/case.yaml
description: "Move from monolithic to microservices with DevOps methodologies and modernization toolkits"
images:
  - image: cp/icpa/icpa-app-nav-apis
  - image: cp/icpa/icpa-app-nav-cmds
  - image: cp/icpa/icpa-app-nav-controller
  - image: cp/icpa/icpa-app-nav-init
  - image: cp/icpa/icpa-app-nav-inv
  - image: cp/icpa/icpa-app-nav-operator
  - image: cp/icpa/icpa-app-nav-ui
  - image: cp/icpa/icpa-app-nav-was-controller
  - image: cp/icpa/icpa-installer-le
  - image: cp/icpa/icpa-landing-le
  - image: cp/icpa/icpa-operator-registry
  - image: cp/icpa/icpa-security-signing-manager
  - image: cp/icpa/sb-checkin-handler
  - image: cp/icpa/sb-gitops-handler
  - image: cp/icpa/sb-init-handler
  - image: cp/icpa/sb-run-manager
  - image: cp/icpa/sb-ui
  - image: cp/icpa/transadv-db
  - image: cp/icpa/transadv-operator
  - image: cp/icpa/transadv-server
  - image: cp/icpa/transadv-ui
  - image: cp/icp-foundation/alertmanager
  - image: cp/icp-foundation/audit-policy-controller
  - image: cp/icp-foundation/collectd-exporter
  - image: cp/icp-foundation/common-web-ui
  - image: cp/icp-foundation/configmap-reload
  - image: cp/icp-foundation/curl
  - image: cp/icp-foundation/dashboard-controller
  - image: cp/icp-foundation/default-http-backend
  - image: cp/icp-foundation/elasticsearch-exporter
  - image: cp/icp-foundation/fluentd
  - image: cp/icp-foundation/grafana
  - image: cp/icp-foundation/iam-policy-administration
  - image: cp/icp-foundation/iam-policy-controller
  - image: cp/icp-foundation/iam-policy-decision
  - image: cp/icp-foundation/ibm-licensing
  - image: cp/icp-foundation/ibm-mongodb
  - image: cp/icp-foundation/ibm-mongodb-exporter
  - image: cp/icp-foundation/ibm-mongodb-install
  - image: cp/icp-foundation/ibm-mt-acct-enforcer
  - image: cp/icp-foundation/ibmservices-operator
  - image: cp/icp-foundation/icp-audit-service
  - image: cp/icp-foundation/icp-catalog-ui
  - image: cp/icp-foundation/icp-cert-manager-acmesolver
  - image: cp/icp-foundation/icp-cert-manager-cainjector
  - image: cp/icp-foundation/icp-cert-manager-controller
  - image: cp/icp-foundation/icp-cert-manager-webhook
  - image: cp/icp-foundation/icp-cert-policy-controller
  - image: cp/icp-foundation/icp-configmap-watcher
  - image: cp/icp-foundation/icp-elasticsearch-oss
  - image: cp/icp-foundation/icp-filebeat-oss
  - image: cp/icp-foundation/icp-helm-api
  - image: cp/icp-foundation/icp-helm-repo
  - image: cp/icp-foundation/icp-helm-rudder
  - image: cp/icp-foundation/icp-iam-onboarding
  - image: cp/icp-foundation/icp-identity-manager
  - image: cp/icp-foundation/icp-identity-provider
  - image: cp/icp-foundation/icp-inception
  - image: cp/icp-foundation/icp-initcontainer
  - image: cp/icp-foundation/icp-kibana-oss
  - image: cp/icp-foundation/icp-logstash-oss
  - image: cp/icp-foundation/icp-management-ingress
  - image: cp/icp-foundation/icp-memcached
  - image: cp/icp-foundation/icp-oidcclient-watcher
  - image: cp/icp-foundation/icp-platform-api
  - image: cp/icp-foundation/icp-platform-auth
  - image: cp/icp-foundation/icp-platform-header
  - image: cp/icp-foundation/icp-secret-watcher
  - image: cp/icp-foundation/indices-cleaner
  - image: cp/icp-foundation/kubectl
  - image: cp/icp-foundation/kube-state-metrics
  - image: cp/icp-foundation/logging-pki-init
  - image: cp/icp-foundation/logstash-liveness-probe
  - image: cp/icp-foundation/mcm-kui-proxy
  - image: cp/icp-foundation/metering-data-manager
  - image: cp/icp-foundation/metering-mcmui
  - image: cp/icp-foundation/metering-ui
  - image: cp/icp-foundation/nginx-ingress-controller
  - image: cp/icp-foundation/node-exporter
  - image: cp/icp-foundation/prometheus
  - image: cp/icp-foundation/prometheus-config-reloader
  - image: cp/icp-foundation/prometheus-controller
  - image: cp/icp-foundation/prometheus-operator
  - image: cp/icp-foundation/system-healthcheck-service
  - image: cp/icp-foundation/tiller
  - image: cp/mf-operator
  - image: cp/mfpf-analytics
  - image: cp/mfpf-analytics-recvr
  - image: cp/mfpf-appcenter
  - image: cp/mfpf-dbinit
  - image: cp/mfpf-elasticsearch
  - image: cp/mfpf-liveupdate
  - image: cp/mfpf-push
  - image: cp/mfpf-server
  - image: ibmcom/busybox
  - image: ibmcom/opencontent-common-utils
