
# The SecurityContextConstraints for the IBM Db2 Big SQL Add-On
# https://docs.openshift.com/container-platform/3.11/rest_api/apis-security.openshift.io/v1.SecurityContextConstraints.html

apiVersion: security.openshift.io/v1
kind: SecurityContextConstraints
metadata:
  annotations:
    kubernetes.io/description: SCC for IBM Db2 Big SQL Add-On LDAP container
  labels:
    app: db2-bigsql
  name: bigsql-ldap

allowedCapabilities:
  - CHOWN
  - DAC_OVERRIDE
  - FOWNER
  - KILL
  - NET_BIND_SERVICE
  - SETGID
  - SETUID

priority: 1

runAsUser:
  type: MustRunAs
  uid: 55

seLinuxContext:
  type: MustRunAs

volumes:
  - persistentVolumeClaim
  - secret
