commands:
- set resources deployment iis-xmetarepo --requests=cpu=1 --limits=cpu=3,memory=30Gi 
- set resources deployment  iis-services --requests=cpu=3
- set resources sts is-en-conductor --requests=cpu=3,memory=4Gi --limits=cpu=8,memory=16Gi
