commands:
- set resources deployment iis-xmetarepo --requests=cpu=1 --limits=cpu=2,memory=20Gi
- set resources deployment  iis-services --requests=cpu=2
- set resources sts is-en-conductor --requests=cpu=2,memory=3Gi --limits=cpu=6,memory=12Gi
